/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "HALL1_A_aliases.h"
#include "HALL1_A.h"
#include "HALL1_B_aliases.h"
#include "HALL1_B.h"
#include "HALL1_C_aliases.h"
#include "HALL1_C.h"
#include "DRIVE1_HA_aliases.h"
#include "DRIVE1_HA.h"
#include "DRIVE1_LA_aliases.h"
#include "DRIVE1_LA.h"
#include "DRIVE1_HB_aliases.h"
#include "DRIVE1_HB.h"
#include "DRIVE1_LB_aliases.h"
#include "DRIVE1_LB.h"
#include "DRIVE1_HC_aliases.h"
#include "DRIVE1_HC.h"
#include "DRIVE1_LC_aliases.h"
#include "DRIVE1_LC.h"
#include "DRIVE1.h"
#include "HALL2_A_aliases.h"
#include "HALL2_A.h"
#include "HALL2_B_aliases.h"
#include "HALL2_B.h"
#include "HALL2_C_aliases.h"
#include "HALL2_C.h"
#include "DRIVE2_HA_aliases.h"
#include "DRIVE2_HA.h"
#include "DRIVE2_LA_aliases.h"
#include "DRIVE2_LA.h"
#include "DRIVE2_HB_aliases.h"
#include "DRIVE2_HB.h"
#include "DRIVE2_LB_aliases.h"
#include "DRIVE2_LB.h"
#include "DRIVE2_HC_aliases.h"
#include "DRIVE2_HC.h"
#include "DRIVE2_LC_aliases.h"
#include "DRIVE2_LC.h"
#include "DRIVE2.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

