/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "HA1_aliases.h"
#include "HA1.h"
#include "HB1_aliases.h"
#include "HB1.h"
#include "HC1_aliases.h"
#include "HC1.h"
#include "LA1_aliases.h"
#include "LA1.h"
#include "LB1_aliases.h"
#include "LB1.h"
#include "LC1_aliases.h"
#include "LC1.h"
#include "HALL_A1_aliases.h"
#include "HALL_A1.h"
#include "HALL_B1_aliases.h"
#include "HALL_B1.h"
#include "HALL_C1_aliases.h"
#include "HALL_C1.h"
#include "REVERSE1_aliases.h"
#include "REVERSE1.h"
#include "PWM1_aliases.h"
#include "PWM1.h"
#include "HA2_aliases.h"
#include "HA2.h"
#include "HB2_aliases.h"
#include "HB2.h"
#include "HC2_aliases.h"
#include "HC2.h"
#include "LA2_aliases.h"
#include "LA2.h"
#include "LB2_aliases.h"
#include "LB2.h"
#include "LC2_aliases.h"
#include "LC2.h"
#include "HALL_A2_aliases.h"
#include "HALL_A2.h"
#include "HALL_B2_aliases.h"
#include "HALL_B2.h"
#include "HALL_C2_aliases.h"
#include "HALL_C2.h"
#include "REVERSE2_aliases.h"
#include "REVERSE2.h"
#include "PWM2_aliases.h"
#include "PWM2.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

