/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LEFT_HALL_A_aliases.h"
#include "LEFT_HALL_A.h"
#include "LEFT_HALL_B_aliases.h"
#include "LEFT_HALL_B.h"
#include "LEFT_HALL_C_aliases.h"
#include "LEFT_HALL_C.h"
#include "LEFT_HA_aliases.h"
#include "LEFT_HA.h"
#include "LEFT_LA_aliases.h"
#include "LEFT_LA.h"
#include "LEFT_HB_aliases.h"
#include "LEFT_HB.h"
#include "LEFT_LB_aliases.h"
#include "LEFT_LB.h"
#include "LEFT_HC_aliases.h"
#include "LEFT_HC.h"
#include "LEFT_LC_aliases.h"
#include "LEFT_LC.h"
#include "LEFT_DIR_aliases.h"
#include "LEFT_DIR.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

